owner: BAM-karaokebox
repo: bam-upptime
user-agent: BAM-karaokebox

sites:
  - name: BKB / BAM Karaoke Box / Website
    url: https://www.bam-karaokebox.com
  - name: BKB / BAM Karaoke Box / Backoffice
    url: https://backend.bam-karaokebox.com
  - name: BKB / BAM Karaoke To Go
    url: https://www.bam-karaoketogo.com
    expectedStatusCodes:
      - 200
      - 301
      - 403
  - name: BKB / BAM Karaoke Online
    url: https://www.bam-karaokeonline.com
    expectedStatusCodes:
      - 200
      - 403
  - name: BKB / BAM Karaoke Online (preproduction)
    url: https://www.app.preproduction.bam-karaokeonline.com
  - name: BKB / BAM Karaoke Online (staging)
    url: https://www.app.staging.bam-karaokeonline.com
  - name: TSL / The Songs Laboratory
    url: https://www.thesongslaboratory.com
  - name: TSL / TSL Karaoke
    url: https://www.tslkaraoke.com
  - name: TSL / TSL Karaoke (preproduction)
    url: https://www.app.preproduction.tslkaraoke.com
  - name: TSL / TSL Karaoke (staging)
    url: https://www.app.staging.tslkaraoke.com
  - name: TSL / TSL Platform / Backend API
    url: https://backend.api.bam-karaokeonline.com
  - name: TSL / TSL Platform / Backend API (preproduction)
    url: https://backend.api.preproduction.bam-karaokeonline.com
  - name: TSL / TSL Platform / Backend API (staging)
    url: https://backend.api.staging.bam-karaokeonline.com
  - name: TSL / TSL Platform / Liana API
    url: https://forest.api.bam-karaokeonline.com
  - name: TSL / TSL Platform / Liana API (preproduction)
    url: https://forest.api.preproduction.bam-karaokeonline.com
  - name: TSL / TSL Platform / Liana API (staging)
    url: https://forest.api.staging.bam-karaokeonline.com
  - name: TSL / PallyCon / Multi-DRM Licence Manager
    url: https://license.pallycon.com/ri/licenseManager.do

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  #cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /bam-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Status Monitor for Singtime's online presence.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
