owner: BAM-karaokebox
repo: bam-upptime
user-agent: BAM-karaokebox

sites:
  - name: BAM Karaoke Box (web)
    url: https://www.bam-karaokebox.com
  - name: BAM Karaoke To Go
    url: https://www.bam-karaoketogo.com
  - name: BAM Karaoke Online (staging)
    url: https://www.app.staging.bam-karaokeonline.com/
  - name: TSL Pro
    url: https://www.tslkaraoke.com/
  - name: TSL Pro (staging)
    url: https://staging.tslkaraoke.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  #cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /bam-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Status Monitor for Singtime's online presence.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
